const express =require("express")
const db = require("./confiq/db")
const cors = require("cors")
const app = express()
require("dotenv").config({path:"./.env"})
db()
app.use(cors())
app.use(express.json())  // request.body madhe data takun det ahe
app.use(express.static("public"))
app.use("/user", require("./routes/userRoutes"))
app.use("/blog", require("./routes/BlogRouter"))
app.use("/gallery", require("./routes/galleryRoute"))
app.use("/docs", require("./routes/docRouter"))
const PORT = process.env.PORT ||5000
app.listen(PORT, console.log(`SERVER RUNNING http://localhost:${PORT}`))